env:
  browser: false
  node: true
  es6: true
  jest: true
plugins:
  - "@typescript-eslint"
  - "functional"
  - "total-functions"
  - "prettier"
  - import
extends:
  - "eslint:recommended"
  - "typed-fp"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: "./tsconfig.json"
rules:
  "import/order":
    - error
    - alphabetize:
        order: asc
  "import/export":
    - off
  "prettier/prettier":
    - error
    - trailingComma: all
      printWidth: 79
