name: docker_build_push

on:
  push:
    branches: chore/add-ci

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          docker build . -t adelabs/node-raml-mocker
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install
      - name: Release
        env:
          DOCKER_USERNAME: ${{ secrets.ADELABS_DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.ADELABS_DOCKER_TOKEN }}
        run: npx semantic-release