name: docker_build_push

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.ADELABS_DOCKER_USER }}
          password: ${{ secrets.ADELABS_DOCKER_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ADELABS_DOCKER_USER }}/node-raml-mocker:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}