name: docker_build_push

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build . -t adelabs/node-raml-mocker:latest
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: yarn install
      - name: Release
        env:
          DOCKER_USERNAME: adelabs
          DOCKER_PASSWORD: ${{ secrets.ADELABS_DOCKER_TOKEN }}
        run: |
          npx semantic-release
