name: e2e_tests

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Build
        run: |
          docker build . -t adelabs/node-raml-mocker:ci-test

      - name: Start Docker image
        run: |
          docker run -d -p 5001:5001 -p 5002:5002 -v ${PWD}/fixtures/raml:/home/runner/artifacts/api -v ${PWD}/fixtures/transformers:/home/runner/artifacts/transformers adelabs/node-raml-mocker:ci-test

      - name: Install dependencies
        run: yarn install

      - name: Run jest e2e test
        run: yarn e2e-test
